name: Deploy

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}  
        script: |
          cd /home/admin
          git fetch origin
          git checkout production
          git pull origin production
          sudo chown -R ubuntu:ubuntu /home/admin
          sudo npm install
          sudo npm run build
          sudo pm2 reload admin
